### ISSUE TITLE
No Vehicle was shown, and current position was hidden

### ISSUE THREAD

**Issue by sinsa92** [regenbogen-ice/frontend#16]
I was riding the ICE 371 today, which got cancelled from basel on and then continued as IC 1083 to Interlaken. In the ICE Portal it was shown though, that the train is currently travelling as ICE 371 (with around 45 min of delay, because now it's driving in the timetable of the IC61 1083). The DB HAFAS Data also backed this: https://reiseauskunft.bahn.de/bin/traininfo.exe/dn/455424/421770/443312/69848/80, together with bahn.expert: https://bahn.expert/details/ICE%20371/2023-03-13T10:17:00.000+01:00. There was a slight difference tho, as the IC61 1083 does not stop in Liestal, so our ICE did not stop aswell.
When I visited https://regenbogen-ice.de/trip/ICE/371, I got no vehicle and no current position shown:
![grafik](https://user-images.githubusercontent.com/36137659/224783310-b8228917-575a-4572-8503-7b2b42acf498.png)

It would be cool, if there would be a hint with the delay, or just a message if the position is unknown, same with the vehicle.

**Comment by AdriDevelopsThings** [comment]
Hello,

thank you for submitting this issue. It exists because the newest train is shown in this view (the train of tomorrow is already fetched, so this train is shown). This acting is a part of the [API](https://github.com/regenbogen-ice/api). We are currently rewriting our API and backend, so it would be a better idea to consider this issue in the new code instead of fixing it in the current API.
